server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql:///mv
    username: root
    password: xth

logging:
  level:
    com.jin: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-not-delete-value: 0
      logic-delete-value: 1
