server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql:///mv
    username: root
    password: "020313"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    com.jin: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-not-delete-value: 0
      logic-delete-value: 1
